# Generated by Django 5.0.6 on 2025-05-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Efectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=210)),
                ('material', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=210)),
                ('caracteristicas', models.CharField(max_length=210)),
                ('estandares', models.CharField(max_length=210)),
            ],
        ),
    ]
