# Generated by Django 5.0.6 on 2025-05-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Efectos', '0002_casco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casco',
            name='peso',
            field=models.FloatField(),
        ),
    ]
